"""Added isCurrent

Revision ID: 3adc03ce1827
Revises: 7738ee003a35
Create Date: 2024-11-19 21:22:11.262380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3adc03ce1827'
down_revision = '7738ee003a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_current', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_current')

    # ### end Alembic commands ###
