"""Image Updates

Revision ID: 471337a3d75a
Revises: 9894234a4cc8
Create Date: 2024-11-17 14:32:15.134110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '471337a3d75a'
down_revision = '9894234a4cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_images')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    op.create_table('project_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('caption', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_project_images_project_id_projects'),
    sa.PrimaryKeyConstraint('id', name='pk_project_images')
    )
    # ### end Alembic commands ###
