"""Add new fields

Revision ID: 60801599e3e4
Revises: 3adc03ce1827
Create Date: 2024-11-19 21:34:36.782750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60801599e3e4'
down_revision = '3adc03ce1827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
