"""Skills

Revision ID: 7738ee003a35
Revises: 471337a3d75a
Create Date: 2024-11-19 21:04:21.626505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7738ee003a35'
down_revision = '471337a3d75a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_skills', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_skills_project_id_projects', type_='foreignkey')
        batch_op.drop_constraint('fk_project_skills_skill_id_skills', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_project_skills_skill_id_skills'), 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_project_skills_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_skills', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_project_skills_project_id_projects'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_project_skills_skill_id_skills'), type_='foreignkey')
        batch_op.create_foreign_key('fk_project_skills_skill_id_skills', 'skills', ['skill_id'], ['id'])
        batch_op.create_foreign_key('fk_project_skills_project_id_projects', 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###
