"""Add features column

Revision ID: 9894234a4cc8
Revises: 1ab5bc11c054
Create Date: 2024-11-15 12:14:38.659066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9894234a4cc8'
down_revision = '1ab5bc11c054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('features', sa.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=255), nullable=True))
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('role')
        batch_op.drop_column('location')
        batch_op.drop_column('features')

    # ### end Alembic commands ###
